; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_CHARMANDER ; 4
	const DEX_CHARMELEON ; 5
	const DEX_CHARIZARD  ; 6
	const DEX_SQUIRTLE   ; 7
	const DEX_WARTORTLE  ; 8
	const DEX_BLASTOISE  ; 9
	const DEX_CATERPIE   ; 10
	const DEX_METAPOD    ; 11
	const DEX_BUTTERFREE ; 12
	const DEX_WEEDLE     ; 13
	const DEX_KAKUNA     ; 14
	const DEX_BEEDRILL   ; 15
	const DEX_PIDGEY     ; 16
	const DEX_PIDGEOTTO  ; 17
	const DEX_PIDGEOT    ; 18
	const DEX_RATTATA    ; 19
	const DEX_RATICATE   ; 20
	const DEX_SPEAROW    ; 21
	const DEX_FEAROW     ; 22
	const DEX_EKANS      ; 23
	const DEX_ARBOK      ; 24
	const DEX_PIKACHU    ; 25
	const DEX_RAICHU     ; 26
	const DEX_SANDSHREW  ; 27
	const DEX_SANDSLASH  ; 28
	const DEX_NIDORAN_F  ; 29
	const DEX_NIDORINA   ; 30
	const DEX_NIDOQUEEN  ; 31
	const DEX_NIDORAN_M  ; 32
	const DEX_NIDORINO   ; 33
	const DEX_NIDOKING   ; 34
	const DEX_CLEFAIRY   ; 35
	const DEX_CLEFABLE   ; 36
	const DEX_VULPIX     ; 37
	const DEX_NINETALES  ; 38
	const DEX_JIGGLYPUFF ; 39
	const DEX_WIGGLYTUFF ; 40
	const DEX_ZUBAT      ; 41
	const DEX_GOLBAT     ; 42
	const DEX_CROBAT     ; 43
	const DEX_ODDISH     ; 44
	const DEX_GLOOM      ; 45
	const DEX_VILEPLUME  ; 46
	const DEX_PARAS      ; 47
	const DEX_PARASECT   ; 48
	const DEX_VENONAT    ; 49
	const DEX_VENOMOTH   ; 50
	const DEX_DIGLETT    ; 51
	const DEX_DUGTRIO    ; 52
	const DEX_MEOWTH     ; 53
	const DEX_PERSIAN    ; 54
	const DEX_PSYDUCK    ; 55
	const DEX_GOLDUCK    ; 56
	const DEX_MANKEY     ; 57
	const DEX_PRIMEAPE   ; 58
	const DEX_GROWLITHE  ; 59
	const DEX_ARCANINE   ; 60
	const DEX_POLIWAG    ; 61
	const DEX_POLIWHIRL  ; 62
	const DEX_POLIWRATH  ; 63
	const DEX_ABRA       ; 64
	const DEX_KADABRA    ; 65
	const DEX_ALAKAZAM   ; 66
	const DEX_MACHOP     ; 67
	const DEX_MACHOKE    ; 68
	const DEX_MACHAMP    ; 69
	const DEX_BELLSPROUT ; 70
	const DEX_WEEPINBELL ; 71
	const DEX_VICTREEBEL ; 72
	const DEX_TENTACOOL  ; 73
	const DEX_TENTACRUEL ; 74
	const DEX_GEODUDE    ; 75
	const DEX_GRAVELER   ; 76
	const DEX_GOLEM      ; 77
	const DEX_PONYTA     ; 78
	const DEX_RAPIDASH   ; 79
	const DEX_SLOWPOKE   ; 80
	const DEX_SLOWBRO    ; 81
	const DEX_MAGNEMITE  ; 82
	const DEX_MAGNETON   ; 83
	const DEX_FARFETCHD  ; 84
	const DEX_DODUO      ; 85
	const DEX_DODRIO     ; 86
	const DEX_SEEL       ; 87
	const DEX_DEWGONG    ; 88
	const DEX_GRIMER     ; 89
	const DEX_MUK        ; 90
	const DEX_SHELLDER   ; 91
	const DEX_CLOYSTER   ; 92
	const DEX_GASTLY     ; 93
	const DEX_HAUNTER    ; 94
	const DEX_GENGAR     ; 95
	const DEX_ONIX       ; 96
	const DEX_DROWZEE    ; 97
	const DEX_HYPNO      ; 98
	const DEX_KRABBY     ; 99
	const DEX_KINGLER    ; 100
	const DEX_VOLTORB    ; 101
	const DEX_ELECTRODE  ; 102
	const DEX_EXEGGCUTE  ; 103
	const DEX_EXEGGUTOR  ; 104
	const DEX_CUBONE     ; 105
	const DEX_MAROWAK    ; 106
	const DEX_HITMONLEE  ; 107
	const DEX_HITMONCHAN ; 108
	const DEX_LICKITUNG  ; 109
	const DEX_KOFFING    ; 110
	const DEX_WEEZING    ; 111
	const DEX_RHYHORN    ; 112
	const DEX_RHYDON     ; 113
	const DEX_RHYPERIOR  ; 114
	const DEX_CHANSEY    ; 115
	const DEX_TANGELA    ; 116
	const DEX_KANGASKHAN ; 117
	const DEX_HORSEA     ; 118
	const DEX_SEADRA     ; 119
	const DEX_GOLDEEN    ; 120
	const DEX_SEAKING    ; 121
	const DEX_STARYU     ; 122
	const DEX_STARMIE    ; 123
	const DEX_MR_MIME    ; 124
	const DEX_SCYTHER    ; 125
	const DEX_JYNX       ; 126
	const DEX_ELECTABUZZ ; 127
	const DEX_MAGMAR     ; 128
	const DEX_PINSIR     ; 129
	const DEX_TAUROS     ; 130
	const DEX_MAGIKARP   ; 131
	const DEX_GYARADOS   ; 132
	const DEX_LAPRAS     ; 133
	const DEX_DITTO      ; 134
	const DEX_EEVEE      ; 135
	const DEX_VAPOREON   ; 136
	const DEX_JOLTEON    ; 137
	const DEX_FLAREON    ; 138
	const DEX_PORYGON    ; 139
	const DEX_OMANYTE    ; 140
	const DEX_OMASTAR    ; 141
	const DEX_KABUTO     ; 142
	const DEX_KABUTOPS   ; 143
	const DEX_AERODACTYL ; 144
	const DEX_SNORLAX    ; 145
	const DEX_ARTICUNO   ; 146
	const DEX_ZAPDOS     ; 147
	const DEX_MOLTRES    ; 148
	const DEX_DRATINI    ; 149
	const DEX_DRAGONAIR  ; 150
	const DEX_DRAGONITE  ; 151
	const DEX_MEWTWO     ; 152
	const DEX_MEW        ; 153

DEF NUM_POKEMON EQU const_value - 1
